language: node_js
node_js:
- 8
branches:
  only:
  - api
notifications:
  email: false
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: auras-app
  on:
    repo: inovecomcoragem/auras-app
    branch: api
